[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.0.0"
  NPM_VERSION = "9.6.4"
  NODE_OPTIONS = "--openssl-legacy-provider"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
